# yaml-language-server: $schema=./pkg/config/config.schema.json

# See pkg/config/config.go for the full list of configuration options.
# This file is used to debugging purposes only.

version: "1"

cache_control_policy:
  enabled: true      

headers:
  subgraphs:
    Primpy:
      request:
        - op: "propagate"
          named: Authorization

# client_header:
#   name: "Helios-Client-Name"
#   version: "Helios-Client-Version"

# telemetry:
#   tracing:
#     response_trace_id:
#       enable: true
#       header_name: "helios-trace-id" # default: "x-wg-trace-id"          

# router_config_path: "./__schemas/config.json"

# modules:
#   myModule:
#     value: 1

# engine:
#   max_concurrent_resolvers: 1024
#   debug:
#     report_websocket_connections: true
#     report_memory_usage: true

# events:
#   providers:
#     nats:
#       - id: default
#         url: "nats://localhost:4222"
#       - id: my-nats
#         url: "nats://localhost:4222"
#     kafka:
#       - id: my-kafka
#         brokers:
#           - "localhost:9092"